Updates to definition
UKHackspaceFoundation/foundation pull request #50
Opened 2019-06-28 14:30 UTC by russss

I've taken the suggestions from the [google doc](https://docs.google.com/document/d/1YyoHdaCyn_zhXaetj70MWVo0WkZ_qKTiwN_cGf7GoY8/edit) and done a bit of general re-writing, but hopefully I've captured most of the comments made. Please drop a comment here if you have any other suggestions.

I think these requirements should be kept fairly minimal - the main purpose of them is to make sure that member spaces are actual non-profits so that the benefits of the HSF aren't abused.

I've taken some wording from the [International Cooperative Alliance Principles](https://www.ica.coop/en/cooperatives/cooperative-identity).

I would like to keep this definition under review as we start accepting spaces, so please don't consider it set in stone. 

Fixes #49

2019-06-28 22:27 UTC, unknowndomain requested changes
I think it should be workshop, not workspace per last nights conversation.

2019-06-30 09:12 UTC, idnorton approved these changes
Looks good to me, streamlined the definition and answered a number of questions along the way.

Gets a :+1: from me

2019-06-30 09:12 UTC, idnorton commented on define.md
> -    * is an unincorporated or incorporated association,
Did we ditch this in favour of bank account?

2019-06-30 09:17 UTC, idnorton commented on define.md
> -    * is an unincorporated or incorporated association,
Discussed in telegram and this was replaced with:

> * is a non-profit association

Along with the requirement for a bank account which automatically requires some degree of legal structure so I'm happy.

2019-06-30 09:17 UTC, idnorton commented
Thanks for your work on this @russss

2019-06-30 09:23 UTC, castaway reviewed
Looking good and much more generalised - I think we should ensure some key words (eg "association") are linked back to the glossary and listed with the specific meaning.. Or better, we add a second page that contains help notes on each of the items, as to how they are checked/verified, to ensure the meaning is understood

2019-06-30 09:32 UTC, merged